server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://192.168.99.115:5432/postgres
    username: postgres
    password: postgres
  main:
    allow-circular-references: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update