apiVersion: batch/v1
kind: Job
metadata:
  name: "homework3-postgres-job"
spec:
  template:
    metadata:
      name: "homework3-postgres-job"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          command:
            - sh
            - "-c"
            - |
              psql postgres://postgres:postgres@hw2-postgresql/postgres <<'EOF'
                DROP SCHEMA public CASCADE;
                CREATE SCHEMA public;
                create table if not exists users (id serial primary key, first_name varchar(100), last_name varchar(100), email varchar(50), phone varchar(25));
                alter table users owner to otus_hw2;