apiVersion: batch/v1
kind: Job
metadata:
  name: otus-homework3-initdb
spec:
  template:
    metadata:
      name: otus-homework3-initdb
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          env:
            - name: DATABASE_URI
              value: postgresql://postgres:postgres@postgres/postgres?sslmode=disable
            - name: DATABASE_NAME
              value: postgres
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              psql postgresql://postgres:postgres@postgres/postgres?sslmode=disable <<'EOF'
                create table users (id serial primary key, username varchar, firstName varchar, lastName varchar, email varchar, phone varchar);
              EOF
  backoffLimit: 2