apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-homework3-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-homework3
  template:
    metadata:
      labels:
        app: otus-homework3
    spec:
      containers:
        - name: otus-homework3
          image: yalekseev1994/microservice-study:1.0.8-SNAPSHOT
          env:
            - name: spring.datasource.url
              valueFrom:
                secretKeyRef:
                  name: otus-homework3-secret
                  key: DATABASE_URI
            - name: spring.datasource.username
              valueFrom:
                configMapKeyRef:
                  name: otus-homework3-config
                  key: DATABASE_USER
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: otus-homework3-secret
                  key: DATABASE_PASSWORD
          ports:
            - containerPort: 8000